services:
  app:
    image: ghcr.io/mikhail-angelov/codev:latest
    container_name: codev
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:3020:3020"
    networks:
      - proxy-net
    labels:
      monic.enabled: "true"
      monic.check: "http"
      monic.check_http_url: "https://codev.bconf.com"
      monic.name: "codev.bconf.com"
      redoproxy.enabled: "true"
      redoproxy.domain: "codev.bconf.com"
      redoproxy.port: 3020
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    command: npm start
  
networks:
  proxy-net:
    external: true